### ISSUE TITLE
Installation of ovmenu-compman fails

### ISSUE THREAD

**Issue by Scumi** [kedder/openvario-compman#1]
When trying to install ovmenu-compman via opkg ppa, the installation fails. 

Image is a self-baked one for the 7" Texim display (openvario-7-CH070), but with no other modifications to the source code.

Sorry for the bad image quality, can't do better with my phone somehow.

![IMG_20200324_193706](https://user-images.githubusercontent.com/26870072/77465488-f9ebdf00-6e08-11ea-873d-ae849b05de14.jpg)

**Comment by kedder** [comment]
Oooh, I think I know why. For some weird reason, openvario has its own menu for all 4 variants of openvario. And the only way to extend the menu is to patch the menu script to insert another option.

And the patch does not apply cleanly for 7-CH070 :man_facepalming: 

Eh, I'll think what we can do here.

**Comment by kedder** [comment]
@Scumi I've updated the `ovmenu-compman` package to version 1.1, please try again:

```
opkg update
opkg install ovmenu-compman
```

Let me know if it works now.

**Comment by Scumi** [comment]
Unfortunately not.

![IMG_20200325_184146](https://user-images.githubusercontent.com/26870072/77568081-624dc580-6ec8-11ea-99af-19ca83187ab8.jpg)

**Comment by kedder** [comment]
Hm, this doesn't make sense. I've installed `ovmenu-ng.sh` for 7-CH070 and ovmenu-compman installed just fine. Did you modify your `ovmenu-ng.sh`? Can you post a copy of this script?

**Comment by kedder** [comment]
Or better yet, you can use this to install the original version of the ovmenu-ng.sh:

```
wget https://dpaste.org/rp10/raw -O - | tr -d "\r" > /opt/bin/ovmenu-ng.sh
```

But still, I'd like to confirm your `/opt/bin/ovmenu-ng.sh` is changed from the original image.

**Comment by Scumi** [comment]
Installation worked after installing the original version of ovmenu-ng.sh. Maybe there was some kind of leftover from the failed install attempts (didn't check unfortunately).
